version: "3"

services:
  backend:
    image: marketing-llm-api:latest
    restart: always
    build:
      context: ./backend
    depends_on:
      - postgres
    environment:
      - username_db = "postgres"
      - password = $POSTGRES_PASSWORD
      - host = "postgres"
      - port = 5432
      - database = "marketing-llm"
    ports:
      - "8080:8000"

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5433:5432"
    volumes:
      - ./backend/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - /data/marketing_postgres:/var/lib/postgresql/data

  frontend:
    image: marketing-llm-frontend:latest
    build:
      context: ./frontend
    depends_on:
      - backend

  caddy:
    image: caddy:alpine
    restart: always
    environment:
      DOMAIN: $ECS_DOMAIN
      EMAIL: $EMAIL
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "caddy_data:/data"
      - "caddy_config:/config"

volumes:
  caddy_data:
  caddy_config:
