version: "3"

services:
  backend:
    image: marketing-llm-api:latest
    restart: always
    build:
      context: ./backend
    depends_on:
      - postgres
      - model
    environment:
      username_db: "postgres"
      password: $POSTGRES_PASSWORD
      host: "postgres"
      port: 5432
      database: "postgres"
    ports:
      - "8080:8000"

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5433:5432"
    volumes:
      - ./backend/script_create.sql:/docker-entrypoint-initdb.d/init-user-db.sql
      - /data/marketing_postgres:/var/lib/postgresql/data

  frontend:
    image: marketing-llm-frontend:latest
    build:
      context: ./frontend
    depends_on:
      - backend

  caddy:
    image: caddy:alpine
    restart: always
    environment:
      DOMAIN: $ECS_DOMAIN
      EMAIL: $EMAIL
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "caddy_data:/data"

  model:
    image: marketing-llm:latest
    build:
      context: ./model
    restart: always
    volumes:
      - "/data/marketing_weights/:/weights/"

volumes:
  caddy_data:
