name: Deploy to dev

on: workflow_dispatch

jobs:
  build_images:
    name: Build images
    environment: dev
    runs-on: [self-hosted, dev-server]
    timeout-minutes: 60
    steps:
      - name: Check for actual
        uses: actions/checkout@v4
        with:
          path: .
      - name: build
        run: >
          docker compose build
          --build-arg REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }}
          --no-cache

  run_project:
    name: Run project
    environment: dev
    runs-on: [self-hosted, dev-server]
    timeout-minutes: 10
    needs: build_images
    steps:
      - name: prepare .env file
        run: |
          echo "${{ vars.ECS_ENV_RAW_CONTENT }}" > .env
          echo "${{ secrets.ECS_ENV_DB_PASSWORD }}" >> .env
      - name: run stack
        run: >
          docker compose up
          -d --force-recreate
      - name: cleanup
        run: docker image prune -f
