name: Deploy to cloud

on: workflow_dispatch

jobs:
  build_images:
    name: Build images
    runs-on: [self-hosted, ecs-f976]
    timeout-minutes: 10
    steps:
      - name: Check for actual
        uses: actions/checkout@v4
        with:
          path: .
      - name: build
        run: >
          docker compose build
          --build-arg REACT_APP_API_URL=${{ env.REACT_APP_API_URL }}

  run_project:
    name: Run project
    runs-on: [self-hosted, ecs-f976]
    timeout-minutes: 10
    needs: build_images
    steps:
      - name: prepare .env file
        run: |
          echo ${{ vars.ECS_ENV_RAW_CONTENT }} > .env
          echo ${{ secrets.ECS_ENV_DB_PASSWORD }} >> .env
      - name: run stack
        run: >
          docker compose up
          -d --force-recreate
